/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/self-lint/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": "true,",
        "heroImage": "/tx.jpg",
        "heroText": "yllon",
        "tagline": "前端编码规范工程化",
        "actionText": "立刻进入 →",
        "actionLink": "/coding/html.md",
        "features": [
          {
            "title": "团队编码规范1113",
            "details": "支持对全部前端配置实现一键接入、一键扫描、一键修复、一键升级"
          },
          {
            "title": "支持 Typescript",
            "details": "提供完整的类型注释，帮助您从 0~1 掌握完整的前端规范化"
          },
          {
            "title": "完整的测试用例",
            "details": "配套完整的测试用例，帮助您提升项目健壮性"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-2ef81724",
      "path": "/"
    },
    {
      "title": "HTML 编码规范",
      "frontmatter": {
        "title": "HTML 编码规范",
        "categories": [
          "编码规范"
        ],
        "tags": [
          "编码规范"
        ],
        "author": {
          "name": null,
          "link": null
        }
      },
      "regularPath": "/coding/html.html",
      "relativePath": "coding/html.md",
      "key": "v-556fc722",
      "path": "/coding/html.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 文档",
          "slug": "_1-文档"
        },
        {
          "level": 3,
          "title": "1.1. 文档类型",
          "slug": "_1-1-文档类型"
        },
        {
          "level": 3,
          "title": "1.2. 语言",
          "slug": "_1-2-语言"
        },
        {
          "level": 3,
          "title": "1.3. 元数据",
          "slug": "_1-3-元数据"
        },
        {
          "level": 3,
          "title": "1.4. 资源加载",
          "slug": "_1-4-资源加载"
        },
        {
          "level": 3,
          "title": "1.5. 页面标题",
          "slug": "_1-5-页面标题"
        },
        {
          "level": 2,
          "title": "2. 编码",
          "slug": "_2-编码"
        },
        {
          "level": 3,
          "title": "2.1. 缩进",
          "slug": "_2-1-缩进"
        },
        {
          "level": 3,
          "title": "2.2. 注释",
          "slug": "_2-2-注释"
        },
        {
          "level": 3,
          "title": "2.3. 标签",
          "slug": "_2-3-标签"
        },
        {
          "level": 3,
          "title": "2.4. 属性",
          "slug": "_2-4-属性"
        },
        {
          "level": 3,
          "title": "2.5. 语义化",
          "slug": "_2-5-语义化"
        },
        {
          "level": 3,
          "title": "2.6. 可访问性",
          "slug": "_2-6-可访问性"
        },
        {
          "level": 2,
          "title": "3. 脚手架模板",
          "slug": "_3-脚手架模板"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "TypeScript 编码规范",
      "frontmatter": {
        "title": "TypeScript 编码规范",
        "categories": [
          "编码规范"
        ],
        "tags": [
          "编码规范"
        ],
        "author": {
          "name": null,
          "link": null
        }
      },
      "regularPath": "/coding/typescript.html",
      "relativePath": "coding/typescript.md",
      "key": "v-aaabfe3c",
      "path": "/coding/typescript.html",
      "headers": [
        {
          "level": 2,
          "title": "编码风格",
          "slug": "编码风格"
        }
      ]
    },
    {
      "title": "Node 编码规范",
      "frontmatter": {
        "title": "Node 编码规范",
        "categories": [
          "编码规范"
        ],
        "tags": [
          "编码规范"
        ],
        "author": {
          "name": null,
          "link": null
        }
      },
      "regularPath": "/coding/node.html",
      "relativePath": "coding/node.md",
      "key": "v-41c99402",
      "path": "/coding/node.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 编码风格",
          "slug": "_1-编码风格"
        },
        {
          "level": 2,
          "title": "2. 安全规约",
          "slug": "_2-安全规约"
        },
        {
          "level": 2,
          "title": "3. 最佳实践",
          "slug": "_3-最佳实践"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "CSS 编码规范",
      "frontmatter": {
        "title": "CSS 编码规范",
        "categories": [
          "编码规范"
        ],
        "tags": [
          "编码规范"
        ],
        "author": {
          "name": null,
          "link": null
        }
      },
      "regularPath": "/coding/css.html",
      "relativePath": "coding/css.md",
      "key": "v-69d23cd2",
      "path": "/coding/css.html",
      "headers": [
        {
          "level": 2,
          "title": "1. CSS",
          "slug": "_1-css"
        },
        {
          "level": 3,
          "title": "1.1. 编码风格",
          "slug": "_1-1-编码风格"
        },
        {
          "level": 3,
          "title": "1.2. 选择器",
          "slug": "_1-2-选择器"
        },
        {
          "level": 3,
          "title": "1.3. 属性和属性值",
          "slug": "_1-3-属性和属性值"
        },
        {
          "level": 3,
          "title": "1.4. 其他",
          "slug": "_1-4-其他"
        },
        {
          "level": 2,
          "title": "2. Sass 和 Less",
          "slug": "_2-sass-和-less"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    },
    {
      "title": "JavaScript 编码规范",
      "frontmatter": {
        "title": "JavaScript 编码规范",
        "categories": [
          "编码规范"
        ],
        "tags": [
          "编码规范"
        ],
        "author": null
      },
      "regularPath": "/coding/javascript.html",
      "relativePath": "coding/javascript.md",
      "key": "v-87a4003c",
      "path": "/coding/javascript.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 编码风格",
          "slug": "_1-编码风格"
        },
        {
          "level": 3,
          "title": "1.1. 缩进",
          "slug": "_1-1-缩进"
        },
        {
          "level": 3,
          "title": "1.2. 分号",
          "slug": "_1-2-分号"
        },
        {
          "level": 3,
          "title": "1.3. 逗号",
          "slug": "_1-3-逗号"
        },
        {
          "level": 3,
          "title": "1.4. 块",
          "slug": "_1-4-块"
        },
        {
          "level": 3,
          "title": "1.5. 空格",
          "slug": "_1-5-空格"
        },
        {
          "level": 3,
          "title": "1.6. 空行",
          "slug": "_1-6-空行"
        },
        {
          "level": 3,
          "title": "1.7. 最大字符数和最大行数",
          "slug": "_1-7-最大字符数和最大行数"
        },
        {
          "level": 2,
          "title": "2. 语言特性",
          "slug": "_2-语言特性"
        },
        {
          "level": 3,
          "title": "2.1. 变量声明",
          "slug": "_2-1-变量声明"
        },
        {
          "level": 3,
          "title": "2.2. 原始类型",
          "slug": "_2-2-原始类型"
        },
        {
          "level": 3,
          "title": "2.3. 数组",
          "slug": "_2-3-数组"
        },
        {
          "level": 3,
          "title": "2.4. 对象",
          "slug": "_2-4-对象"
        },
        {
          "level": 3,
          "title": "2.5. 函数",
          "slug": "_2-5-函数"
        },
        {
          "level": 3,
          "title": "2.6. 类",
          "slug": "_2-6-类"
        },
        {
          "level": 3,
          "title": "2.7. 模块",
          "slug": "_2-7-模块"
        },
        {
          "level": 3,
          "title": "2.8. 操作符",
          "slug": "_2-8-操作符"
        },
        {
          "level": 3,
          "title": "2.9. 控制语句",
          "slug": "_2-9-控制语句"
        },
        {
          "level": 3,
          "title": "2.10. 其他",
          "slug": "_2-10-其他"
        },
        {
          "level": 2,
          "title": "3. 注释",
          "slug": "_3-注释"
        },
        {
          "level": 2,
          "title": "4. 命名",
          "slug": "_4-命名"
        },
        {
          "level": 2,
          "title": "参考资料",
          "slug": "参考资料"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/tx.jpg",
    "nav": [
      {
        "text": "首页",
        "link": "/index.md"
      },
      {
        "text": "编码规范",
        "items": [
          {
            "text": "CSS 编码规范",
            "link": "/coding/css.md"
          },
          {
            "text": "JavaScript 编码规范",
            "link": "/coding/javascript.md"
          },
          {
            "text": "Node 编码规范",
            "link": "/coding/node.md"
          },
          {
            "text": "Typescript 编码规范",
            "link": "/coding/typescript.md"
          }
        ]
      },
      {
        "text": "工程规范",
        "items": [
          {
            "text": "Git 规范",
            "link": "/engineering/git.md"
          },
          {
            "text": "文档规范",
            "link": "/engineering/doc.md"
          },
          {
            "text": "CHANGELOG 规范",
            "link": "/engineering/changelog.md"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "编码规范",
        "children": [
          {
            "title": "CSS 编码规范",
            "path": "/coding/css.md"
          },
          {
            "title": "JavaScript 编码规范",
            "path": "/coding/javascript.md"
          },
          {
            "title": "Node 编码规范",
            "path": "/coding/node.md"
          },
          {
            "title": "Typescript 编码规范",
            "path": "/coding/typescript.md"
          }
        ]
      },
      {
        "title": "工程规范",
        "children": [
          {
            "title": "Git 规范",
            "path": "/engineering/git.md"
          },
          {
            "title": "文档规范",
            "path": "/engineering/doc.md"
          },
          {
            "title": "CHANGELOG 规范",
            "path": "/engineering/changelog.md"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "yllon1",
      "description": "前端编码规范工程化",
      "path": "/"
    }
  }
}